#!/usr/bin/env perl

use strict;
use warnings;

my @dirs = (
    'Movies',
    'Pictures',
    'Documents',
    'Library',
    'Desktop',
);

for my $dir (@dirs) {
#    my $dest = "/Volumes/Hepler-Home-Media-1/$dir";
    my $dest = "/Volumes/tgi-time-machine-backups/todd-account/final";
    my $cmd = "rsync -av $dir $dest";
    print "$cmd\n";
    system($cmd);
}
